### ISSUE TITLE
Atividade Equipe 10

### ISSUE THREAD

**Issue by lucasbaccan** [djonathanb/unipar-2021-trabalho-plano#3]
# Equipe 10

## Integrantes
[João Kirst](https://github.com/joaoalexandre2)
[Lucas Baccan](https://github.com/lucasbaccan)
[Luiz Fernando Brogliatto Ferreira](https://github.com/luiz0067)

## E10.1 - Solicitar Transporte

Como um **Usuário**, preciso ***solicitar transporte*** para encaminhar passageiros entre diferentes cidades.

### Critérios de Aceite

- A solicitação deve ser solicitada para uma carteirinha válida.
- A soliciação deve conter a cidade de origem e destino.
- Os tipos de transporte são Ambulância, UTI Móvel ou Aereo.
- O transporte aéreo só é permitido se contratado no plano.

## E10.2 - Cancelar solicitação de Transporte

Como um **Usuário**, preciso ***cancelar uma solicitar de transporte*** caso tenha sido lançada indevidamente.

### Critérios de Aceite

- A solicitação não pode ter sido autorizada.

## E10.3 - Autorizar Transporte

Como um **Agente**, preciso ***cancelar uma solicitação transporte*** caso detecte qualquer irregularidade.

### Critérios de Aceite

- O transporte deve ter sido solicitado previamente pelo Usuário.

---

## TODO LIST
- [ ] E10.1 - Solicitar Transporte
- [ ] E10.2 - Cancelar solicitação de Transporte
- [ ] E10.3 - Autorizar Transporte

## Dependen de:
- [ ] E2.1 - Cadastro de Plano (Precisamos da informação de trasporte aerio)
- [ ] E3.1 - Cadastro de Contrato (É onde se cria um usuario)
- [ ] E5.1 - Emissão de Carteirinha (Precisamos de carteirinha valida)

## Perguntar ao Professor
- [ ] A aplicação vai trabalhar com banco de dados relacional ou não relacional, o que é o h2database?
- [ ] Como que vai vir o resultado da informação, JSON, XML, HTML?
- [ ] Como que se cria um endpoin

**Comment by lucasbaccan** [comment]
![TrabalhoPos-Simulacao](https://user-images.githubusercontent.com/2676484/139555534-267aa5e0-cb32-4593-9117-472a78ec85f4.png)

**Comment by lucasbaccan** [comment]
![TrabalhoPos-ModeloDominio drawio](https://user-images.githubusercontent.com/2676484/139555541-22cd7ea0-0bb3-43db-b950-9098d26c7986.png)
